name: etnn
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - gudhi=3.8.0
  - matplotlib=3.7.2
  - networkx=3.1
  - numpy=1.22.4
  - pandas=1.4.2
  - pip=23.2.1
  - python=3.10
  - pytorch=2.1.0
  - pytorch-cuda=11.8  # comment for MacOS
  - rdkit
  - scipy=1.11.3
  - pip:
    - git+https://github.com/pyt-team/TopoNetX@cede811485aefcff1d013dbb94942e8f92ac5d05
    - tqdm==4.66.1
    - ipykernel
    - numba>=0.5
    - wandb==0.15.12
    - hydra-core>=1.3
    - torch_geometric>=2.5