name: empsn
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.7.2
  - networkx=3.1
  - pandas=1.4.2
  - pip=23.2.1
  - python=3.10
  - pytorch=2.1.0
  - rdkit
  - scipy=1.7.3
  - seaborn
  - tqdm=4.66.1
  - wandb=0.15.12
  - pip:
      - gudhi==3.8.0
      - jupyter
      - numpy==1.22.4
      - torch-geometric==2.4.0
      - torch-scatter==2.1.2
