defaults:
  - _self_
  - experiment: experiment_1

dataset:
  # these values can be overwritten by the experiments
  lifters: []
  supercell: false
  neighbor_types: ["max"]  # Subset of ["+1", "-1", "min", "max"]
  connectivity: "self"  # Choice in [self, all_to_all]

# task name will make more sense when we introduce the spatial CC
task_name: QM9
dataset_name: ${hydra:runtime.choices.dataset}
experiment_name: ${hydra:runtime.choices.experiment}
target: alpha  # Options: targets = ["mu", "alpha", "homo", "lumo", "gap", "r2", "zpve", "U0", "U", "H", "G", "Cv", "U0_atom", "U_atom", "H_atom", "G_atom", "A", "B", "C"]
train_test_splits: egnn  # Options: [egnn, random]

compile: false
seed: 42

# checkpointing
wandb_entity: null
ckpt_dir: checkpoints
ckpt_prefix: null
force_restart: false

model:
  num_hidden: 128
  num_layers: 7
  normalize_invariants: true
  batch_norm: false
  lean: false
  initial_features: ["hetero"]  # Subset of ["hetero", "mem"]
  visible_dims: null # defaults to all dimensions in the combinatorial complex
  # merge_neighbors: false

training:
  epochs: 350
  batch_size: 96
  weight_decay: 1e-16
  min_lr: 0.0
  num_lr_cycles: 3
  clip_gradients: true
  clip_amount: 1.0
  test_interval: 10
  lr: 5e-4
