#@package _global_
defaults:
  - override /loss_fn: mse

model:
  num_out: 1
  num_hidden: 64
  num_layers: 4
  num_readout_layers: 3
  depth_etnn_layers: 2

optimizer:
  weight_decay: 1e-4

lr_scheduler:
  final_div_factor: 1
