#@package _global_
defaults:
  - override /loss_fn: mse

model:
  num_out: 1
  num_hidden: 8
  num_layers: 4
  num_readout_layers: 1
  depth_etnn_layers: 1

optimizer:
  weight_decay: 1e-10

training:
  clip: null

lr_scheduler:
  final_div_factor: 1

# this one will fail with graphs
dataset:
  transform:
    _target_: torch_geometric.transforms.compose.Compose
    _args_:
      - - _target_: etnn.pm25.utils.create_mask
          _partial_: true
          seed: ${seed}
          rate: 0.25
        - _target_: etnn.pm25.utils.randomize_x0
          _partial_: true
        - _target_: etnn.pm25.utils.x1_labels
          _partial_: true
        - _target_: etnn.pm25.utils.squash_cc
          _partial_: true
          soft: true
