#@package _global_
defaults:
  - override /dataset: pm25-graph

model:
  equivariant: false
  hausdorff: false

dataset:
  _target_: etnn.pm25.utils.SpatialCC
  root: ./data
  force_reload: true
  pre_transform: 
    _target_: etnn.pm25.utils.standardize_cc
    _partial_: true
  transform:
    _target_: torch_geometric.transforms.compose.Compose
    _args_:
      - - _target_: etnn.pm25.utils.create_mask
          _partial_: true
          seed: ${seed}   
        - _target_: etnn.pm25.utils.randomize
          _partial_: true
          keys: ['x_1', 'x_2']
        - _target_: etnn.pm25.utils.squash_cc
          _partial_: true
