# @package _global_
dataset:
  _target_: etnn.pm25.utils.SpatialCC
  root: ./data
  force_reload: true
  pre_transform: 
    _target_: etnn.pm25.utils.standardize_cc
    _partial_: true
  transform:
    _target_: etnn.pm25.utils.create_mask
    seed: ${seed}   
    _partial_: true
