defaults:
  - _self_
  - loss_fn: huber
  - task: spatial-cc2
  - lr: low
  - dataset: pm25-cc
  - arch: arch-cc2-1
  - baseline: invariant

seed: 42
force_restart: false
baseline_name: ${hydra:runtime.choices.baseline}
dataset_name: ${hydra:runtime.choices.dataset}
arch_name: ${hydra:runtime.choices.arch}
loss_fn_name: ${hydra:runtime.choices.loss_fn}
training_name: ${hydra:runtime.choices.training}
ckpt_prefix: null
